server:
  port: 8080

spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - RewritePath=/customer-service/(?<remaining>.*), /api/v1/${remaining}
        - RewritePath=/operation-service/(?<remaining>.*), /api/v1/${remaining}
        - RewritePath=/product-service/(?<remaining>.*), /api/v1/${remaining}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
