spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb+srv://xaleons72_db_user:YKJLPRL4giDOswys@cluster0.bst1l3t.mongodb.net/customerDB?retryWrites=true&w=majority&appName=Cluster0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
