server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://testxal.auth0.com/

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka-server:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.reactive.function.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: routes, health, info