server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      retry:
        max-attempts: 5
        multiplier: 1.5
        initial-interval: 2000
        max-interval: 10000

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/cliente/**
          filters:
            - RewritePath=/api/v1/cliente/(?<remaining>.*), /api/v1/cliente/${remaining}
            - name: CircuitBreaker
              args:
                name: customerServiceCB
                fallbackUri: forward:/fallback/customer
        - id: operation-service
          uri: lb://operation-service
          predicates:
            - Path=/api/v1/operaciones/**
          filters:
            - RewritePath=/api/v1/operaciones/(?<remaining>.*), /api/v1/operaciones/${remaining}
            - name: CircuitBreaker
              args:
                name: operationServiceCB
                fallbackUri: forward:/fallback/operation
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/producto/**
          filters:
            - RewritePath=/api/v1/producto/(?<remaining>.*), /api/v1/producto/${remaining}
            - name: CircuitBreaker
              args:
                name: productServiceCB
                fallbackUri: forward:/fallback/product
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://testxal.auth0.com/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@eureka-server:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web.reactive.function.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
  instances:
    customerServiceCB:              # Nombre de la instancia del Circuit Breaker
      registerHealthIndicator: true # Habilita la exposición de un indicador de salud en /actuator/health
      slidingWindowSize: 5          # Número de llamadas recientes que se usan para calcular la tasa de fallos
      minimumNumberOfCalls: 3       # Número mínimo de llamadas antes de que el CB evalúe si debe abrirse
      failureRateThreshold: 50      # Porcentaje de fallos permitido antes de abrir el CB (50%)
      waitDurationInOpenState: 10s  # Tiempo que el CB permanece abierto antes de intentar un nuevo intento